import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({ 
  weight: '400',
  subsets: ['thai'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
        <body className={inter.className}>
          <div className="flex flex-col min-h-screen">
            <Navbar/>
            <div className="flex-1 overflow-auto">
              {children}
            </div>
          </div>
          <Toaster/>
          </body>
    </html>
  );
}
